Repository Ureka-High-Five/log-reprocessor, pull requests merged in 2025-07, with the labels that each got.

#3 Chore[#2] : ec2 배포
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  docker-compose.yml
Labels: chore

#5 Chore[#3] : Dockerfile 수정
  .github/workflows/ci.yml
  Dockerfile
Labels: chore

#11 Feat[#8]: daily weight resize 후 managed action log 삭제 로직 구현
  app/main.py
  app/repositories/managed_action_log_repository.py
  app/services/scheduler_service.py
Labels: feat

#13 Feat[#10] : 보상 트랜잭션 실패 시 트랜잭션 롤백 로직 추가
  app/__init__.py
  app/logging/__init__.py
  app/main.py
  app/repositories/action_log_repository.py
  app/repositories/user_weight_repository.py
  app/services/log_reprocessor_service.py
Labels: feat

#23 Refactor[#22]: Action Log의 metaInfo 형식이 Dict로 변경됨에 따른 데일리 스케줄러 로직 수정
  app/services/daily_weight_resizer.py
Labels: refactor

#24 Refactor[#21] : 새로운 임베딩 모델로 변경
  .github/workflows/ci.yml
  .gitignore
  app/models/db_w2v_mapper.py
  app/models/word2vec_model.py
  app/services/weight_strategy.py
Labels: refactor
